export const hardcodedMembershipRecords = [
  {
    userName: 'Anna Luk',
    className: 'Painting',
    status: 'Active',
    availableCount: 8,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'John Doe',
    className: 'Music',
    status: 'Expired',
    availableCount: 14,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'Alice Smith',
    className: 'Dance',
    status: 'Expiring',
    availableCount: 3,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'Bob Johnson',
    className: 'Sculpture',
    status: 'Active',
    availableCount: 10,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'Eva Brown',
    className: 'Theater',
    status: 'Expired',
    availableCount: 7,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'Charlie Davis',
    className: 'Photography',
    status: 'Expiring',
    availableCount: 5,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },

  {
    userName: 'User 25',
    className: 'Digital Art',
    status: 'Active',
    availableCount: 12,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'User 26',
    className: 'Film',
    status: 'Expired',
    availableCount: 5,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
  {
    userName: 'User 27',
    className: 'Crafts',
    status: 'Expiring',
    availableCount: 9,
    expirationDate: new Date(),
    actions: ['edit', 'remove'],
  },
];
